---
- name: Add redis PPA and update apt cache
  apt_repository:
    repo: ppa:rwky/redis
    update_cache: yes
    state: present
  tags:
      - install
  when: "not (ansible_distribution == 'Ubuntu' and (ansible_distribution_version|version_compare(14.04, '>')))"

- name: install required system packages
  apt: name={{ item }} state=latest
  with_items:
      - redis-server
  tags:
      - install
